name: "Build Site"
on:
  workflow_dispatch:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Get Dependencies
        run: npm install
      - name: Build React
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist